#!/bin/bash
# -*- shell-script -*-
if [ -d /start.sh.d ]; then
		for f in /start.sh.d/*.sh; do
			  [ -f "$f" ] && . "$f"
		done
fi
export PATH=/usr/local/bundle/bin:$PATH

! [ $# -eq 0 ] && exec $@ || exec /bin/bash -l
