guacd:
  image: glyptodon/guacd:latest
  hostname: guacd
  domainname: 0.infinidim.enterprises
guacdb:
  # TODO: extend the image with guac init.sql commands!
  image: postgres:latest
  hostname: db
  domainname: 0.infinidim.enterprises
  environment:
    - POSTGRES_DB=guacamole_db
    - POSTGRES_USER=guacamole_user
    - POSTGRES_PASSWORD=secret
  ports:
    - "5432:5432"
guacamole:
  image: glyptodon/guacamole:latest
  environment:
    - POSTGRES_DATABASE=guacamole_db
    - POSTGRES_USER=guacamole_user
    - POSTGRES_PASSWORD=secret
  ports:
    - "8080:8080"
  links:
    - guacdb:postgres
    - guacd:guacd
