source "http://rubygems.org"
gem 'configurability'
gem 'datamapper' #, "1.2.0"
gem 'dm-aggregates'
gem 'dm-types' #, git: 'https://github.com/datamapper/dm-types.git' #, "~> 1.2.1"
gem 'dm-observer'
gem 'dm-migrations'
gem 'dm-timestamps'
gem 'dm-serializer' #, "~> 1.2.0"
gem 'dm-mysql-adapter'
gem 'dm-sqlite-adapter'
gem 'sucker_punch'
gem 'httparty'
gem 'rest-client'
gem 'thor'
gem 'ansi'
gem 'yell'
gem 'rmagick'
gem 'rio'
gem 'activesupport' #, "~> 5.0.1"
gem 'uuid'
gem 'actionview' #, "~> 5.0.1"
gem 'digest-crc'
gem 'percentage'
gem 'percentise'
gem 'rubyzip'
gem 'zip-zip'
gem 'serenity-odt', git: 'https://github.com/kremso/serenity.git'
gem 'odf_core', git: 'https://github.com/meinac/odf_core.git'
gem 'yomu'
gem 'escper', git: 'https://github.com/michaelfranzl/ruby-escper.git', branch: 'master'
gem 'pdf-forms'
gem 'google_currency'
gem 'monetize'
gem 'money' #, "~> 5.1.1"
gem 'chronic'
gem 'chronic_duration'
gem 'ri_cal', git: 'https://github.com/KonaTeam/ri_cal.git'
gem 'time_difference'
gem 'true-random', git: 'https://github.com/voipscout/true-random.git', branch: 'master'
gem 'dicom', git: 'https://github.com/dicom/ruby-dicom.git', branch: 'master'
gem 'nokogiri'
gem 'xpath', git: 'https://github.com/abotalov/xpath.git', branch: 'infrastructure'
gem 'fuzzy_match', git: 'https://github.com/seamusabshere/fuzzy_match.git'
gem 'ruby-gmail' #, git: 'https://github.com/myobie/ruby-gmail.git'
gem "sentry-raven"
gem 'tty-progressbar'

group :development do
  gem 'rubocop'
  gem "rspec"
  gem "rdoc"
  gem "cucumber"
  gem "bundler"
  gem "simplecov"
  gem 'binding_of_caller'
  gem "pry", git: 'https://github.com/pry/pry.git'
  gem "ruby-termios"
  gem "pry-doc"
  gem "pry-coolline" #, git: 'https://github.com/pry/pry-coolline.git'
  gem 'pry-rescue', git: 'https://github.com/ConradIrwin/pry-rescue.git'
  gem 'pry-macro'
  gem 'pry-toys'
  gem 'awesome_print'
  gem 'hirb'
end
